function catInit(){
catActualizarTabla()}function catActualizarTabla(){document.getElementById(`cat-grid-requisitos`).innerHTML=catCriterios.map((n,i)=>`
    <div class="cat-card" id="cat-card-${i}" style="border-top: 3px solid ${n.color};">
      <img src="${n.img}" class="cat-card-img">
      <h3 style="color:${n.color}">${n.n}</h3>
      <div class="metric-row"><span>Cal. Promedio Mín:</span><b>${i===0?`—`:n.r}</b></div>
      <div class="metric-row"><span>Tasa Canc. Máx:</span><b>${i===0?`—`:n.c+`%`}</b></div>
      <div class="metric-row"><span>Tasa Acep. Mín:</span><b>${i===0?`—`:n.a+`%`}</b></div>
      <div class="metric-row"><span>Viajes Compl. Mín:</span><b>${i===0?`—`:n.v}</b></div>
    </div>
  `).join(``)}function catUpdateScore(type){let val=parseFloat(document.getElementById(`cat-`+type+`_in`).value)||0,percent=0,color=`#ff4d4d`;type===`v`&&(percent=val/100*100),type===`r`&&(percent=val/5*100),type===`c`&&(percent=Math.max(0,100-val)),type===`a`&&(percent=val),percent>=90?color=`#22c55e`:percent>=60&&(color=`#fbbf24`);let fill=document.getElementById(`cat-score_`+type);fill.style.width=Math.min(percent,100)+`%`,fill.style.backgroundColor=color}function catUpdateAllScores(){[`v`,`r`,`c`,`a`].forEach(catUpdateScore)}function catAnalizar(){let v=parseInt(document.getElementById(`cat-v_in`).value)||0,r=parseFloat(document.getElementById(`cat-r_in`).value)||0,c=parseFloat(document.getElementById(`cat-c_in`).value)||0,a=parseFloat(document.getElementById(`cat-a_in`).value)||0,actual=0;
v>=100&&r>=4.8&&c<=12&&a>=30?actual=2:v>=25&&r>=4.5&&c<=22&&a>=15&&(actual=1);
let cat=catCriterios[actual],nxt=catCriterios[actual+1]||null,faltanStr=``;if(nxt){let f=[];v<nxt.v&&f.push(`completar ${nxt.v-v} viajes más (meta: ${nxt.v})`),r<nxt.r&&f.push(`mejorar el rating a ${nxt.r} (actual: ${r})`),c>nxt.c&&f.push(`reducir la cancelación al ${nxt.c}% o menos (actual: ${c}%)`),a<nxt.a&&f.push(`subir la aceptación al ${nxt.a}% (actual: ${a}%)`),faltanStr=f.length>0?f.join(`, `):`¡ya cumple todos los criterios! El sistema actualizará su categoría en el próximo corte.`}else faltanStr=`¡ya se encuentra en la categoría máxima!`;let nxtNombre=nxt?nxt.n:`máximo nivel`;document.getElementById(`cat-t1`).innerText=`Rider, su categoría actual es ${cat.n}. Para ascender a ${nxtNombre} requiere: ${faltanStr}.`,document.getElementById(`cat-t2`).innerText=`¡Hola! Comprendo su interés por mejorar su nivel. Actualmente se encuentra en ${cat.n}, pero para calificar como ${nxtNombre} el próximo mes, el enfoque debe estar en: ${faltanStr}. ¡Estamos para apoyarle!`,document.getElementById(`cat-t3`).innerText=`Estimado Rider, hemos revisado su progreso y va por buen camino como ${cat.n}. Si logra fortalecer los siguientes puntos: ${faltanStr}, muy pronto alcanzará el nivel de ${nxtNombre}. ¡Siga adelante!`,document.getElementById(`cat-t4`).innerText=`Le explico con detalle: el sistema evalúa 4 criterios globales para todas las ciudades. Usted tiene ${v} viajes${nxt?` (meta: ${nxt.v})`:``}; su rating es ${r}${nxt?` (mínimo requerido: ${nxt.r})`:``}; su tasa de cancelación es ${c}%${nxt?` (límite: ${nxt.c}%)`:``}; y su aceptación es ${a}%${nxt?` (mínimo: ${nxt.a}%)`:``}. ${nxt?`Para pasar a ${nxtNombre}: ${faltanStr}.`:`¡Está en el nivel máximo!`}`,document.getElementById(`cat-resultados`).classList.remove(`cat-hidden`),document.querySelectorAll(`.cat-card`).forEach(card=>card.classList.remove(`active`));let cardEl=document.getElementById(`cat-card-`+actual);cardEl&&cardEl.classList.add(`active`)}function catToggleTheme(){document.documentElement.setAttribute(`data-theme`,document.getElementById(`catCheckbox`).checked?`dark`:`light`)}function catLimpiarTodo(){document.querySelectorAll(`#cat-module input`).forEach(i=>{i.value=``}),document.getElementById(`cat-resultados`).classList.add(`cat-hidden`),catUpdateAllScores()}function catShowTab(id,btn){document.querySelectorAll(`#cat-module .tab-content`).forEach(c=>c.classList.add(`cat-hidden`)),document.querySelectorAll(`#cat-module .tab-btn`).forEach(b=>b.classList.remove(`active`)),document.getElementById(id).classList.remove(`cat-hidden`),btn.classList.add(`active`)}function catCopiar(id){navigator.clipboard.writeText(document.getElementById(id).innerText).then(()=>alert(`Respuesta copiada con éxito`))}
