// ═══════════════════════════════════════════════════════════
let kitEditKey=null,kitModoNuevo=!1;const KIT_LS_KEY=`admincx_kits_contenido`,KIT_ESTADOS={stock:{label:`✅ EN STOCK`,bg:`var(--verde-p)`,color:`var(--negro-2)`,border:`rgba(56,206,166,.4)`,barColor:`var(--verde)`,precioColor:`var(--verde)`,opacity:`1`},disponible:{label:`✅ DISPONIBLE`,bg:`var(--azul-p)`,color:`var(--azul)`,border:`rgba(39,40,131,.2)`,barColor:`var(--azul)`,precioColor:`var(--azul)`,opacity:`1`},"sin-etiquetas":{label:`❌ SIN ETIQUETAS`,bg:`var(--rosa-p)`,color:`var(--rosa)`,border:`rgba(215,29,92,.25)`,barColor:`var(--rosa)`,precioColor:`var(--gris-4)`,opacity:`.85`},agotado:{label:`⚠️ AGOTADO`,bg:`var(--amber-p)`,color:`var(--amber)`,border:`rgba(217,119,6,.25)`,barColor:`var(--amber)`,precioColor:`var(--gris-4)`,opacity:`.85`}};
function kitLsGetAll(){try{return JSON.parse(localStorage.getItem(KIT_LS_KEY)||`{}`)}catch{return{}}}function kitLsSet(key,data){try{let all=kitLsGetAll();all[key]=data,localStorage.setItem(KIT_LS_KEY,JSON.stringify(all))}catch(e){console.warn(`[KIT] localStorage write failed:`,e)}}function kitLsDel(key){try{let all=kitLsGetAll();delete all[key],localStorage.setItem(KIT_LS_KEY,JSON.stringify(all))}catch{}}
async function kitCargarContenido(){
let apiOk=!1;try{let res=await fetch(`/api/contenido?seccion=indumentaria-kits`);if(res.ok){let json=await res.json();if(json.success&&json.data){apiOk=!0;
try{localStorage.removeItem(KIT_LS_KEY)}catch{}json.data.forEach(doc=>{kitAplicarDoc(doc),kitLsSet(doc.key,doc)})}}}catch(e){console.warn(`[KIT] API no disponible:`,e.message)}
if(!apiOk){let local=kitLsGetAll();Object.values(local).forEach(doc=>kitAplicarDoc(doc))}}
function kitAplicarDoc(doc){
if(doc.visible===!1){let cardDel=document.querySelector(`[data-kit-key="`+doc.key+`"]`);cardDel&&(cardDel.style.transition=`opacity .3s,transform .3s`,cardDel.style.opacity=`0`,cardDel.style.transform=`scale(.95)`,setTimeout(()=>cardDel.remove(),320)),kitLsDel(doc.key);return}let card=document.querySelector(`[data-kit-key="`+doc.key+`"]`);if(card||=kitCrearCardDOM(doc.key),!card)return;
let nombreVal=doc.nombre||doc.titulo||``;if(nombreVal){let el=card.querySelector(`.kit-nombre`);el&&(el.textContent=nombreVal)}
if(doc.emoji){let el=card.querySelector(`.kit-emoji`);el&&(el.textContent=doc.emoji)}
if(doc.precio!==void 0&&doc.precio!==``){let el=card.querySelector(`.kit-precio`);if(el){el.textContent=doc.precio;let cfg=KIT_ESTADOS[doc.estado||`stock`];el.style.color=cfg?cfg.precioColor:`var(--verde)`}}
if(doc.desc!==void 0){let el=card.querySelector(`.kit-desc`);el&&(el.textContent=doc.desc)}
doc.estado&&kitAplicarEstado(card,doc.estado)}
function kitAplicarEstado(card,estado){let cfg=KIT_ESTADOS[estado];if(!cfg)return;let badge=card.querySelector(`.kit-badge`);badge&&(badge.textContent=cfg.label,badge.style.background=cfg.bg,badge.style.color=cfg.color,badge.style.border=`1.5px solid `+cfg.border,badge.dataset.estado=estado);let bar=card.querySelector(`.kit-bar`);bar&&(bar.style.background=cfg.barColor),card.style.opacity=cfg.opacity;
let precio=card.querySelector(`.kit-precio`);precio&&(precio.style.color=cfg.precioColor)}
function kitCrearCardDOM(key){let grid=document.getElementById(`kit-grid`);if(!grid)return null;let div=document.createElement(`div`);div.setAttribute(`data-kit-key`,key),div.style.cssText=`background:var(--blanco);border:1.5px solid var(--borde);border-radius:16px;padding:24px;box-shadow:var(--shadow);position:relative;overflow:hidden`,div.innerHTML=`
                <div class="kit-bar" style="position:absolute;top:0;left:0;right:0;height:4px;background:var(--verde)"></div>
                <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:16px">
                    <div class="kit-emoji" style="font-size:2.2rem">📦</div>
                    <span class="kit-badge" data-estado="stock" style="background:var(--verde-p);color:var(--negro-2);border:1.5px solid rgba(56,206,166,.4);border-radius:999px;padding:4px 14px;font-size:.72rem;font-weight:900;font-family:var(--font-secondary)">✅ EN STOCK</span>
                </div>
                <div class="kit-nombre" style="font-family:var(--font-main);font-size:.95rem;font-weight:900;color:var(--negro);margin-bottom:8px;line-height:1.3">NUEVO KIT</div>
                <div class="kit-precio" style="font-family:var(--font-display);font-size:2rem;letter-spacing:2px;color:var(--verde);margin-bottom:8px">$0.00</div>
                <div class="kit-desc" style="font-family:var(--font-secondary);font-size:.78rem;color:var(--gris-4);font-weight:600">Descripción del kit</div>
                <div class="kit-admin-btns" style="display:none;margin-top:14px;gap:8px;flex-wrap:wrap">
                    <button onclick="kitOpenEdit('${key}',this)" style="padding:5px 13px;border:1.5px solid var(--azul);border-radius:7px;background:#fff;color:var(--azul);font-size:.78rem;font-weight:800;cursor:pointer">✏️ Editar</button>
                    <button onclick="kitEliminar('${key}')" style="padding:5px 13px;border:1.5px solid var(--rosa);border-radius:7px;background:#fff;color:var(--rosa);font-size:.78rem;font-weight:800;cursor:pointer">🗑️ Eliminar</button>
                </div>
            `;
let addCard=document.getElementById(`kit-add-card`);return grid.insertBefore(div,addCard),typeof loginType<`u`&&loginType===`admin`&&(div.querySelector(`.kit-admin-btns`).style.display=`flex`),div}
function kitInyectarBotonesAdmin(){let isAdmin=typeof loginType<`u`&&loginType===`admin`;document.querySelectorAll(`[data-kit-key]`).forEach(function(card){let btns=card.querySelector(`.kit-admin-btns`);btns&&(btns.style.display=isAdmin?`flex`:`none`)});
let addCard=document.getElementById(`kit-add-card`);addCard&&(addCard.style.display=isAdmin?`flex`:`none`)}
function kitEstadoChange(){let val=document.querySelector(`input[name="kit-edit-estado"]:checked`)?.value;[`stock`,`disponible`,`sin-etiquetas`,`agotado`].forEach(function(s){let lbl=document.getElementById(`kit-st-lbl-`+s);if(!lbl)return;let cfg=KIT_ESTADOS[s];s===val?(lbl.style.background=cfg.bg,lbl.style.borderColor=cfg.barColor,lbl.style.color=cfg.color):(lbl.style.background=``,lbl.style.borderColor=`#DDE8E3`,lbl.style.color=``)})}
function kitOpenEdit(key,btnEl){kitModoNuevo=!1,kitEditKey=key;let card=document.querySelector(`[data-kit-key="`+key+`"]`);if(!card)return;document.getElementById(`kit-edit-modal-title`).textContent=`✏️ Editar Kit`,document.getElementById(`kit-edit-modal-key`).textContent=`key: `+key,document.getElementById(`kit-edit-emoji`).value=(card.querySelector(`.kit-emoji`)||{}).textContent?.trim()||``,document.getElementById(`kit-edit-nombre`).value=(card.querySelector(`.kit-nombre`)||{}).textContent?.trim()||``,document.getElementById(`kit-edit-precio`).value=(card.querySelector(`.kit-precio`)||{}).textContent?.trim()||``,document.getElementById(`kit-edit-desc`).value=(card.querySelector(`.kit-desc`)||{}).textContent?.trim()||``;
let badgeEstado=card.querySelector(`.kit-badge`)?.dataset?.estado||`stock`,radio=document.querySelector(`input[name="kit-edit-estado"][value="`+badgeEstado+`"]`);radio&&(radio.checked=!0,kitEstadoChange()),document.getElementById(`kit-edit-error`).style.display=`none`,document.getElementById(`kit-edit-success`).style.display=`none`,document.getElementById(`kit-edit-modal`).style.display=`flex`}
function kitOpenNuevo(){kitModoNuevo=!0,kitEditKey=`kit-`+Date.now(),document.getElementById(`kit-edit-modal-title`).textContent=`➕ Agregar nuevo kit`,document.getElementById(`kit-edit-modal-key`).textContent=`key: `+kitEditKey,document.getElementById(`kit-edit-emoji`).value=``,document.getElementById(`kit-edit-nombre`).value=``,document.getElementById(`kit-edit-precio`).value=``,document.getElementById(`kit-edit-desc`).value=``;let radio=document.querySelector(`input[name="kit-edit-estado"][value="stock"]`);radio&&(radio.checked=!0,kitEstadoChange()),document.getElementById(`kit-edit-error`).style.display=`none`,document.getElementById(`kit-edit-success`).style.display=`none`,document.getElementById(`kit-edit-modal`).style.display=`flex`}function kitCloseEdit(){document.getElementById(`kit-edit-modal`).style.display=`none`,kitEditKey=null,kitModoNuevo=!1}
async function kitGuardarEdit(){let saveBtn=document.getElementById(`kit-edit-save-btn`),errEl=document.getElementById(`kit-edit-error`),succEl=document.getElementById(`kit-edit-success`);errEl.style.display=`none`,succEl.style.display=`none`;let nombre=document.getElementById(`kit-edit-nombre`).value.trim();if(!nombre){errEl.textContent=`⚠️ El nombre del kit es obligatorio.`,errEl.style.display=`block`;return}saveBtn.textContent=`⏳ Guardando...`,saveBtn.disabled=!0;let estado=document.querySelector(`input[name="kit-edit-estado"]:checked`)?.value||`stock`,payload={seccion:`indumentaria-kits`,key:kitEditKey,emoji:document.getElementById(`kit-edit-emoji`).value.trim()||`📦`,nombre,precio:document.getElementById(`kit-edit-precio`).value.trim(),desc:document.getElementById(`kit-edit-desc`).value.trim(),estado,visible:!0};kitLsSet(kitEditKey,payload),kitModoNuevo&&kitCrearCardDOM(kitEditKey),kitAplicarDoc(payload);
let apiOk=!1;try{let json=await(await fetch(`/api/contenido`,{method:`PUT`,headers:{"Content-Type":`application/json`},body:JSON.stringify(payload)})).json();json.success&&(apiOk=!0,json.data&&kitLsSet(kitEditKey,json.data))}catch{console.warn(`[KIT] API no disponible, guardado solo localmente.`)}saveBtn.textContent=`💾 Guardar cambios`,saveBtn.disabled=!1,apiOk?kitCloseEdit():(succEl.textContent=`✅ Guardado localmente. Se sincronizará cuando haya conexión.`,succEl.style.display=`block`,setTimeout(()=>kitCloseEdit(),2500))}
function kitEliminar(key){if(!confirm(`¿Eliminar este kit? Esta acción no se puede deshacer.`))return;
let card=document.querySelector(`[data-kit-key="`+key+`"]`);
card&&(card.style.transition=`opacity .3s,transform .3s`,card.style.opacity=`0`,card.style.transform=`scale(.95)`,setTimeout(()=>card.remove(),320)),kitLsDel(key),fetch(`/api/contenido`,{method:`DELETE`,headers:{"Content-Type":`application/json`},body:JSON.stringify({seccion:`indumentaria-kits`,key})}).catch(()=>{})}
document.getElementById(`kit-edit-modal`).addEventListener(`click`,function(e){e.target===this&&kitCloseEdit()});